<h2>Bienvenido Ingrese sus Datos</h2>

<p><?php $this->flashSession->output() ?></p>

<?php echo $this->tag->form("signup/register"); ?>

    <div class="form-group">
        <label for="nombre">Nombre</label>
        <?php echo $form->render('nombre'); ?>

    </div>

    <div class="form-group">
        <label for="identificacion">Identificación</label>
        <?php echo $form->render('identificacion'); ?>
    </div>

    <div class="form-group">
        <label for="fecha">Fecha de Nacimiento</label>
        <?php echo $form->render('fecha_nacimiento'); ?>
    </div>

    <div class="form-group">
        <label for="genero">Género</label>
        <?php echo $form->render('genero'); ?>
    </div>

    <div class="form-group">
        <label for="estado">Estado Civil</label>
        <?php echo $form->render('estado_civil'); ?>
    </div>

    <div class="form-group">
        <label for="direccion">Dirección</label>
        <?php echo $form->render('direccion'); ?>
    </div>

    <div class="form-group">
        <label for="telefono">Telefono</label>
        <?php echo $form->render('telefono'); ?>
    </div>

    <div class="form-group">
    
        <?php echo $form->render('submit'); ?>

    </div>

</form>