<h2>Bienvenido Ingrese sus Datos</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <div class="form-group">
        <label for="nombre">Nombre</label>
        <?php echo $this->tag->textField(["nombre","class" => "form-control","placeholder" => "Ingrese su Nombre completo"]); ?>
    </div>

    <div class="form-group">
        <label for="identificacion">Identificación</label>
        <?php echo $this->tag->textField(["identificacion","class" => "form-control","placeholder" => "Ingrese su Identificación"]); ?>
    </div>

    <div class="form-group">
        <label for="fecha">Fecha de Nacimiento</label>
        <?php echo $this->tag->textField(["fecha_nacimiento","class" => "form-control","placeholder" => "Ingrese su Fecha de Nacimiento"]); ?>
    </div>

    <div class="form-group">
        <label for="genero">Género</label>
        <?php echo $this->tag->textField(["genero","class" => "form-control","placeholder" => "Ingrese su Género"]); ?>
    </div>

    <div class="form-group">
        <label for="estado">Estado Civil</label>
        <?php echo $this->tag->textField(["estado_civil","class" => "form-control","placeholder" => "Ingrese su Estado Civil"]); ?>
    </div>

    <div class="form-group">
        <label for="direccion">Dirección</label>
        <?php echo $this->tag->textField(["direccion","class" => "form-control","placeholder" => "Ingrese su Dirección"]); ?>
    </div>

    <div class="form-group">
        <label for="telefono">Telefono</label>
        <?php echo $this->tag->textField(["telefono","class" => "form-control","placeholder" => "Ingrese su Telefono"]); ?>
    </div>

    <div class="form-group">
        <?php echo $this->tag->submitButton(["Registro","class" => "btn btn-primary mb-2"]); ?>

    </div>

</form>